"""Official SDK interoperability on synthetic input. SDK/jsonschema are test-only.

Run: uv run --no-project --with 'mcp==2.2.0' --with 'jsonschema==4.26.0' python mcp/verify_sdk.py
"""

import asyncio
import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from jsonschema import Draft202012Validator
from mcp.client.stdio import StdioServerParameters
from test_workflow import request

from mcp import Client

ROOT = Path(__file__).resolve().parent.parent


async def check():
    with tempfile.TemporaryDirectory(prefix="worldbuilding-sdk-") as temporary:
        directory = Path(temporary)
        environment = {**os.environ, "WORLDBUILDING_WORKSPACE": temporary, "WORLDBUILDING_PROJECT_ID": "example",
                       "XDG_STATE_HOME": str(directory / "state")}
        book = directory / "worldbook"
        book.mkdir()
        page = book / "Gate.md"
        page.write_text("---\ntitle: Gate\n---\n# Gate\nThe tide gate consumes salt.\n", encoding="utf-8")
        config = directory / ".worldcheck.json"
        config.write_text(json.dumps({"schema_version": 1, "project_id": "sdk-fixture", "content_root": "worldbook",
                                      "page_globs": ["**/*.md"], "policy_files": []}), encoding="utf-8")
        environment["WORLDCHECK_CONFIG"] = str(config)
        baseline = await asyncio.to_thread(subprocess.run, ["ruby", str(ROOT / "tools/worldcheck/worldcheck"), "check", "--full", "--config", str(config), "--json"],
                                           env=environment, capture_output=True, text=True, encoding="utf-8", check=True)
        assert json.loads(baseline.stdout)["ok"]
        transport = StdioServerParameters(command=sys.executable, args=[str(ROOT / "mcp/server.py")], env=environment, cwd=temporary)
        async with Client(transport, read_timeout_seconds=70) as client:
            tools = (await client.list_tools()).tools
            assert len(tools) == 17
            schemas = {item.name: item for item in tools}
            for item in tools:
                Draft202012Validator.check_schema(item.input_schema)
                Draft202012Validator.check_schema(item.output_schema)

            async def call(name, arguments):
                Draft202012Validator(schemas[name].input_schema).validate(arguments)
                result = await client.call_tool(name, arguments)
                assert not result.is_error, result
                Draft202012Validator(schemas[name].output_schema).validate(result.structured_content)
                return result.structured_content

            state = await call("world_project_template", {"title": "潮闸镇", "seed": "潮闸需要盐"})
            assert (await call("world_validate", {"state": state}))["valid"]
            await call("world_audit", {"state": state})
            await call("world_route", {"state": state})
            await call("world_craft_packet", {"mode": "analyze_excerpt", "source_scope": "synthetic excerpt", "text": "他搬盐上台阶。"})
            await call("world_text_surface_audit", {"text": "他搬盐上台阶。", "scope_manifest": {"scope_kind": "excerpt"}})
            await call("world_craft_review_check", {"source_scope": "synthetic", "coverage_matrix": [], "diagnostic_lenses": [], "findings": []})
            req = request()
            await call("world_evidence_search", {"project_id": "example", "sources": req["context"]["sources"], "query": "潮闸"})
            await call("world_context_packet", req["context"])
            packet = await call("world_write_packet", req)
            # An original synthetic candidate written by the host, not generated by MCP.
            candidate = {"title": "潮闸镇", "content": "清晨，搬盐的车先过潮闸。每户轮值，把当天的盐送到闸边；排班表只记录送盐，不能保证机器绝不损坏。家人若生病，当值者向邻户借一个班，欠班留待下周偿还。盐供应中断时，居民先停不紧急的用闸，检查库存与运盐道路。镇上仍未确定各户应分担多少盐，这一点留给作者选择。",
                         "status": "proposed", "context_hash": packet["context_hash"], "writing_hash": packet["writing_hash"], "citations": []}
            checked = await call("world_candidate_check", {"request": req, "candidate": candidate})
            assert checked["integrity_valid"] and not checked["semantic_truth_verified"]
            saved = await call("world_candidate_save", {"candidate_id": "town", "operation_id": "sdk-op", "expected_head": None,
                                                       "request": req, "candidate": candidate})
            read = await call("world_candidate_read", {"candidate_id": "town", "revision_hash": saved["revision_hash"]})
            assert read["candidate"] == candidate and read["freshness"] == "not_revalidated"
            await call("world_change_impact", {"node_ids": ["rule", "scene"], "changed_ids": ["rule"], "dependencies": [{"from": "scene", "to": "rule"}]})
            assert len((await client.list_prompts()).prompts) == 14
            prompt = await client.get_prompt("worldbuilding_create_world", {"request_json": json.dumps(req)})
            assert "UNSEEN_SECRET" not in prompt.messages[0].content.text
            assert len((await client.list_resources()).resources) == 2
            resource = await client.read_resource("worldbuilding://contract")
            assert "候选空间" in resource.contents[0].text
            assert (await call("worldcheck_status", {}))["ok"]
            page.write_text(page.read_text(encoding="utf-8") + "The market stocks spare salt.\n", encoding="utf-8")
            packet = (await call("worldcheck_prepare_review", {"targets": ["Gate"]}))["packet"]
            receipt = {"receipt_version": "1.0", "packet_hash": packet["packet_hash"], "reviewer": {"kind": "human", "identity": "synthetic-tester"},
                       "verdict": "pass", "findings": [], "omissions": [], "created_at": datetime.now(timezone.utc).isoformat()}
            recorded = await call("worldcheck_record_receipt", {"packet_hash": packet["packet_hash"], "receipt": receipt})
            assert recorded["recorded"]
            assert (await call("worldcheck_status", {}))["ok"]
        print("Official SDK: 17 tool schemas/calls, 14 prompts, 2 resources and synthetic worldbook receipt workflow passed.")


if __name__ == "__main__":
    asyncio.run(check())
